
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Sociology 2e'
tagline:          'from http://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d@10.1 (CC-BY)'
url:              https://github.com/philschatz/sociology-book
origin:           http://cnx.org/contents/02040312-72c8-441e-a685-20e9333f3e1d@10.1

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          10.1

bookviewer:       https://philschatz.com/book-viewer

